#!/bin/bash

# List of all language codes that we're downloading files for
languages=(en fr zh_TW)

# Loop through all languages and download each one's .po file
for language in ${languages[@]}
do
  echo "Downloading file for $language..."
  curl -so Localization/Source/$language.po https://www.transifex.com/tatoeba/tatoeba-ios/stringspo/$language/download/for_use/
done
